### ISSUE TITLE
Template not understood

### ISSUE THREAD

**Issue by sorobedio** [automl-conf/LatexTemplate#1]
are the conference papers double columns or single column page?
the template is single column but there is no discussion on the format of the manuscripts.
It will be great if you can make the template clear  like others major conferences templates  with example of paper structure  including a dummy bib file

**Comment by rmgarnett** [comment]
Conference papers are single column, as illustrated by the output of either `.tex` file in the repository. The files are self-documenting regarding format in the sense that their output is already compliant by design.

The `instructions.tex` file follows the structure of a conference paper with title, authors, abstract, sections and other document divisions, broader impact statement, reproducibility checklist, acknowledgements, supplement, and references. The `instructions.tex` file also does in fact include a dummy `.bib` file embedded in the document and illustrates how you might use `natbib` or `biblatex` to produce a bibliography.
